/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package br.com.hitbra.marketplace.avro.orders;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Order extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Order\",\"namespace\":\"br.com.hitbra.marketplace.avro.orders\",\"fields\":[{\"name\":\"commercial_id\",\"type\":\"string\"},{\"name\":\"order_id\",\"type\":\"string\"},{\"name\":\"order_state\",\"type\":\"string\"},{\"name\":\"shop_id\",\"type\":\"long\"},{\"name\":\"order_lines\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"OrderLine\",\"fields\":[{\"name\":\"order_line_id\",\"type\":\"string\"},{\"name\":\"order_line_state\",\"type\":\"string\"},{\"name\":\"product_sku\",\"type\":\"string\"},{\"name\":\"offer_id\",\"type\":\"long\"},{\"name\":\"offer_sku\",\"type\":\"string\"},{\"name\":\"quantity\",\"type\":\"int\"},{\"name\":\"received_date\",\"type\":[\"long\",\"null\"],\"logicalType\":\"time-millis\"},{\"name\":\"shipped_date\",\"type\":[\"long\",\"null\"],\"logicalType\":\"time-millis\"}]}}},{\"name\":\"shipping_carrier_code\",\"type\":[\"string\",\"null\"]},{\"name\":\"shipping_company\",\"type\":[\"string\",\"null\"]},{\"name\":\"shipping_tracking\",\"type\":[\"string\",\"null\"]},{\"name\":\"shipping_tracking_url\",\"type\":[\"string\",\"null\"]},{\"name\":\"delivery_date\",\"type\":[\"long\",\"null\"],\"logicalType\":\"time-millis\"},{\"name\":\"invoice_access_key\",\"type\":[\"string\",\"null\"]},{\"name\":\"invoice_date\",\"type\":[\"long\",\"null\"],\"logicalType\":\"time-millis\"},{\"name\":\"invoice_line\",\"type\":[\"string\",\"null\"]},{\"name\":\"invoice_number\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence commercial_id;
  @Deprecated public java.lang.CharSequence order_id;
  @Deprecated public java.lang.CharSequence order_state;
  @Deprecated public long shop_id;
  @Deprecated public java.util.List<br.com.hitbra.marketplace.avro.orders.OrderLine> order_lines;
  @Deprecated public java.lang.CharSequence shipping_carrier_code;
  @Deprecated public java.lang.CharSequence shipping_company;
  @Deprecated public java.lang.CharSequence shipping_tracking;
  @Deprecated public java.lang.CharSequence shipping_tracking_url;
  @Deprecated public java.lang.Long delivery_date;
  @Deprecated public java.lang.CharSequence invoice_access_key;
  @Deprecated public java.lang.Long invoice_date;
  @Deprecated public java.lang.CharSequence invoice_line;
  @Deprecated public java.lang.CharSequence invoice_number;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Order() {}

  /**
   * All-args constructor.
   */
  public Order( java.lang.CharSequence commercial_id, java.lang.CharSequence order_id, java.lang.CharSequence order_state, java.lang.Long shop_id, java.util.List<br.com.hitbra.marketplace.avro.orders.OrderLine> order_lines, java.lang.CharSequence shipping_carrier_code, java.lang.CharSequence shipping_company, java.lang.CharSequence shipping_tracking, java.lang.CharSequence shipping_tracking_url, java.lang.Long delivery_date, java.lang.CharSequence invoice_access_key, java.lang.Long invoice_date, java.lang.CharSequence invoice_line, java.lang.CharSequence invoice_number) {
    this.commercial_id = commercial_id;
    this.order_id = order_id;
    this.order_state = order_state;
    this.shop_id = shop_id;
    this.order_lines = order_lines;
    this.shipping_carrier_code = shipping_carrier_code;
    this.shipping_company = shipping_company;
    this.shipping_tracking = shipping_tracking;
    this.shipping_tracking_url = shipping_tracking_url;
    this.delivery_date = delivery_date;
    this.invoice_access_key = invoice_access_key;
    this.invoice_date = invoice_date;
    this.invoice_line = invoice_line;
    this.invoice_number = invoice_number;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return commercial_id;
    case 1: return order_id;
    case 2: return order_state;
    case 3: return shop_id;
    case 4: return order_lines;
    case 5: return shipping_carrier_code;
    case 6: return shipping_company;
    case 7: return shipping_tracking;
    case 8: return shipping_tracking_url;
    case 9: return delivery_date;
    case 10: return invoice_access_key;
    case 11: return invoice_date;
    case 12: return invoice_line;
    case 13: return invoice_number;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: commercial_id = (java.lang.CharSequence)value$; break;
    case 1: order_id = (java.lang.CharSequence)value$; break;
    case 2: order_state = (java.lang.CharSequence)value$; break;
    case 3: shop_id = (java.lang.Long)value$; break;
    case 4: order_lines = (java.util.List<br.com.hitbra.marketplace.avro.orders.OrderLine>)value$; break;
    case 5: shipping_carrier_code = (java.lang.CharSequence)value$; break;
    case 6: shipping_company = (java.lang.CharSequence)value$; break;
    case 7: shipping_tracking = (java.lang.CharSequence)value$; break;
    case 8: shipping_tracking_url = (java.lang.CharSequence)value$; break;
    case 9: delivery_date = (java.lang.Long)value$; break;
    case 10: invoice_access_key = (java.lang.CharSequence)value$; break;
    case 11: invoice_date = (java.lang.Long)value$; break;
    case 12: invoice_line = (java.lang.CharSequence)value$; break;
    case 13: invoice_number = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'commercial_id' field.
   */
  public java.lang.CharSequence getCommercialId() {
    return commercial_id;
  }

  /**
   * Sets the value of the 'commercial_id' field.
   * @param value the value to set.
   */
  public void setCommercialId(java.lang.CharSequence value) {
    this.commercial_id = value;
  }

  /**
   * Gets the value of the 'order_id' field.
   */
  public java.lang.CharSequence getOrderId() {
    return order_id;
  }

  /**
   * Sets the value of the 'order_id' field.
   * @param value the value to set.
   */
  public void setOrderId(java.lang.CharSequence value) {
    this.order_id = value;
  }

  /**
   * Gets the value of the 'order_state' field.
   */
  public java.lang.CharSequence getOrderState() {
    return order_state;
  }

  /**
   * Sets the value of the 'order_state' field.
   * @param value the value to set.
   */
  public void setOrderState(java.lang.CharSequence value) {
    this.order_state = value;
  }

  /**
   * Gets the value of the 'shop_id' field.
   */
  public java.lang.Long getShopId() {
    return shop_id;
  }

  /**
   * Sets the value of the 'shop_id' field.
   * @param value the value to set.
   */
  public void setShopId(java.lang.Long value) {
    this.shop_id = value;
  }

  /**
   * Gets the value of the 'order_lines' field.
   */
  public java.util.List<br.com.hitbra.marketplace.avro.orders.OrderLine> getOrderLines() {
    return order_lines;
  }

  /**
   * Sets the value of the 'order_lines' field.
   * @param value the value to set.
   */
  public void setOrderLines(java.util.List<br.com.hitbra.marketplace.avro.orders.OrderLine> value) {
    this.order_lines = value;
  }

  /**
   * Gets the value of the 'shipping_carrier_code' field.
   */
  public java.lang.CharSequence getShippingCarrierCode() {
    return shipping_carrier_code;
  }

  /**
   * Sets the value of the 'shipping_carrier_code' field.
   * @param value the value to set.
   */
  public void setShippingCarrierCode(java.lang.CharSequence value) {
    this.shipping_carrier_code = value;
  }

  /**
   * Gets the value of the 'shipping_company' field.
   */
  public java.lang.CharSequence getShippingCompany() {
    return shipping_company;
  }

  /**
   * Sets the value of the 'shipping_company' field.
   * @param value the value to set.
   */
  public void setShippingCompany(java.lang.CharSequence value) {
    this.shipping_company = value;
  }

  /**
   * Gets the value of the 'shipping_tracking' field.
   */
  public java.lang.CharSequence getShippingTracking() {
    return shipping_tracking;
  }

  /**
   * Sets the value of the 'shipping_tracking' field.
   * @param value the value to set.
   */
  public void setShippingTracking(java.lang.CharSequence value) {
    this.shipping_tracking = value;
  }

  /**
   * Gets the value of the 'shipping_tracking_url' field.
   */
  public java.lang.CharSequence getShippingTrackingUrl() {
    return shipping_tracking_url;
  }

  /**
   * Sets the value of the 'shipping_tracking_url' field.
   * @param value the value to set.
   */
  public void setShippingTrackingUrl(java.lang.CharSequence value) {
    this.shipping_tracking_url = value;
  }

  /**
   * Gets the value of the 'delivery_date' field.
   */
  public java.lang.Long getDeliveryDate() {
    return delivery_date;
  }

  /**
   * Sets the value of the 'delivery_date' field.
   * @param value the value to set.
   */
  public void setDeliveryDate(java.lang.Long value) {
    this.delivery_date = value;
  }

  /**
   * Gets the value of the 'invoice_access_key' field.
   */
  public java.lang.CharSequence getInvoiceAccessKey() {
    return invoice_access_key;
  }

  /**
   * Sets the value of the 'invoice_access_key' field.
   * @param value the value to set.
   */
  public void setInvoiceAccessKey(java.lang.CharSequence value) {
    this.invoice_access_key = value;
  }

  /**
   * Gets the value of the 'invoice_date' field.
   */
  public java.lang.Long getInvoiceDate() {
    return invoice_date;
  }

  /**
   * Sets the value of the 'invoice_date' field.
   * @param value the value to set.
   */
  public void setInvoiceDate(java.lang.Long value) {
    this.invoice_date = value;
  }

  /**
   * Gets the value of the 'invoice_line' field.
   */
  public java.lang.CharSequence getInvoiceLine() {
    return invoice_line;
  }

  /**
   * Sets the value of the 'invoice_line' field.
   * @param value the value to set.
   */
  public void setInvoiceLine(java.lang.CharSequence value) {
    this.invoice_line = value;
  }

  /**
   * Gets the value of the 'invoice_number' field.
   */
  public java.lang.CharSequence getInvoiceNumber() {
    return invoice_number;
  }

  /**
   * Sets the value of the 'invoice_number' field.
   * @param value the value to set.
   */
  public void setInvoiceNumber(java.lang.CharSequence value) {
    this.invoice_number = value;
  }

  /** Creates a new Order RecordBuilder */
  public static br.com.hitbra.marketplace.avro.orders.Order.Builder newBuilder() {
    return new br.com.hitbra.marketplace.avro.orders.Order.Builder();
  }
  
  /** Creates a new Order RecordBuilder by copying an existing Builder */
  public static br.com.hitbra.marketplace.avro.orders.Order.Builder newBuilder( br.com.hitbra.marketplace.avro.orders.Order.Builder other) {
    return new br.com.hitbra.marketplace.avro.orders.Order.Builder(other);
  }
  
  /** Creates a new Order RecordBuilder by copying an existing Order instance */
  public static br.com.hitbra.marketplace.avro.orders.Order.Builder newBuilder( br.com.hitbra.marketplace.avro.orders.Order other) {
    return new br.com.hitbra.marketplace.avro.orders.Order.Builder(other);
  }
  
  /**
   * RecordBuilder for Order instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Order>
    implements org.apache.avro.data.RecordBuilder<Order> {

    private java.lang.CharSequence commercial_id;
    private java.lang.CharSequence order_id;
    private java.lang.CharSequence order_state;
    private long shop_id;
    private java.util.List<br.com.hitbra.marketplace.avro.orders.OrderLine> order_lines;
    private java.lang.CharSequence shipping_carrier_code;
    private java.lang.CharSequence shipping_company;
    private java.lang.CharSequence shipping_tracking;
    private java.lang.CharSequence shipping_tracking_url;
    private java.lang.Long delivery_date;
    private java.lang.CharSequence invoice_access_key;
    private java.lang.Long invoice_date;
    private java.lang.CharSequence invoice_line;
    private java.lang.CharSequence invoice_number;

    /** Creates a new Builder */
    private Builder() {
      super(br.com.hitbra.marketplace.avro.orders.Order.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(br.com.hitbra.marketplace.avro.orders.Order.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.commercial_id)) {
        this.commercial_id = data().deepCopy(fields()[0].schema(), other.commercial_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.order_id)) {
        this.order_id = data().deepCopy(fields()[1].schema(), other.order_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.order_state)) {
        this.order_state = data().deepCopy(fields()[2].schema(), other.order_state);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.shop_id)) {
        this.shop_id = data().deepCopy(fields()[3].schema(), other.shop_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.order_lines)) {
        this.order_lines = data().deepCopy(fields()[4].schema(), other.order_lines);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.shipping_carrier_code)) {
        this.shipping_carrier_code = data().deepCopy(fields()[5].schema(), other.shipping_carrier_code);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.shipping_company)) {
        this.shipping_company = data().deepCopy(fields()[6].schema(), other.shipping_company);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.shipping_tracking)) {
        this.shipping_tracking = data().deepCopy(fields()[7].schema(), other.shipping_tracking);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.shipping_tracking_url)) {
        this.shipping_tracking_url = data().deepCopy(fields()[8].schema(), other.shipping_tracking_url);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.delivery_date)) {
        this.delivery_date = data().deepCopy(fields()[9].schema(), other.delivery_date);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.invoice_access_key)) {
        this.invoice_access_key = data().deepCopy(fields()[10].schema(), other.invoice_access_key);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.invoice_date)) {
        this.invoice_date = data().deepCopy(fields()[11].schema(), other.invoice_date);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.invoice_line)) {
        this.invoice_line = data().deepCopy(fields()[12].schema(), other.invoice_line);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.invoice_number)) {
        this.invoice_number = data().deepCopy(fields()[13].schema(), other.invoice_number);
        fieldSetFlags()[13] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Order instance */
    private Builder(br.com.hitbra.marketplace.avro.orders.Order other) {
            super(br.com.hitbra.marketplace.avro.orders.Order.SCHEMA$);
      if (isValidValue(fields()[0], other.commercial_id)) {
        this.commercial_id = data().deepCopy(fields()[0].schema(), other.commercial_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.order_id)) {
        this.order_id = data().deepCopy(fields()[1].schema(), other.order_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.order_state)) {
        this.order_state = data().deepCopy(fields()[2].schema(), other.order_state);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.shop_id)) {
        this.shop_id = data().deepCopy(fields()[3].schema(), other.shop_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.order_lines)) {
        this.order_lines = data().deepCopy(fields()[4].schema(), other.order_lines);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.shipping_carrier_code)) {
        this.shipping_carrier_code = data().deepCopy(fields()[5].schema(), other.shipping_carrier_code);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.shipping_company)) {
        this.shipping_company = data().deepCopy(fields()[6].schema(), other.shipping_company);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.shipping_tracking)) {
        this.shipping_tracking = data().deepCopy(fields()[7].schema(), other.shipping_tracking);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.shipping_tracking_url)) {
        this.shipping_tracking_url = data().deepCopy(fields()[8].schema(), other.shipping_tracking_url);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.delivery_date)) {
        this.delivery_date = data().deepCopy(fields()[9].schema(), other.delivery_date);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.invoice_access_key)) {
        this.invoice_access_key = data().deepCopy(fields()[10].schema(), other.invoice_access_key);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.invoice_date)) {
        this.invoice_date = data().deepCopy(fields()[11].schema(), other.invoice_date);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.invoice_line)) {
        this.invoice_line = data().deepCopy(fields()[12].schema(), other.invoice_line);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.invoice_number)) {
        this.invoice_number = data().deepCopy(fields()[13].schema(), other.invoice_number);
        fieldSetFlags()[13] = true;
      }
    }

    /** Gets the value of the 'commercial_id' field */
    public java.lang.CharSequence getCommercialId() {
      return commercial_id;
    }
    
    /** Sets the value of the 'commercial_id' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder setCommercialId( java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.commercial_id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'commercial_id' field has been set */
    public boolean hasCommercialId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'commercial_id' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder clearCommercialId() {
      commercial_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'order_id' field */
    public java.lang.CharSequence getOrderId() {
      return order_id;
    }
    
    /** Sets the value of the 'order_id' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder setOrderId( java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.order_id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'order_id' field has been set */
    public boolean hasOrderId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'order_id' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder clearOrderId() {
      order_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'order_state' field */
    public java.lang.CharSequence getOrderState() {
      return order_state;
    }
    
    /** Sets the value of the 'order_state' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder setOrderState( java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.order_state = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'order_state' field has been set */
    public boolean hasOrderState() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'order_state' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder clearOrderState() {
      order_state = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'shop_id' field */
    public java.lang.Long getShopId() {
      return shop_id;
    }
    
    /** Sets the value of the 'shop_id' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder setShopId( long value) {
      validate(fields()[3], value);
      this.shop_id = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'shop_id' field has been set */
    public boolean hasShopId() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'shop_id' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder clearShopId() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'order_lines' field */
    public java.util.List<br.com.hitbra.marketplace.avro.orders.OrderLine> getOrderLines() {
      return order_lines;
    }
    
    /** Sets the value of the 'order_lines' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder setOrderLines( java.util.List<br.com.hitbra.marketplace.avro.orders.OrderLine> value) {
      validate(fields()[4], value);
      this.order_lines = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'order_lines' field has been set */
    public boolean hasOrderLines() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'order_lines' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder clearOrderLines() {
      order_lines = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'shipping_carrier_code' field */
    public java.lang.CharSequence getShippingCarrierCode() {
      return shipping_carrier_code;
    }
    
    /** Sets the value of the 'shipping_carrier_code' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder setShippingCarrierCode( java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.shipping_carrier_code = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'shipping_carrier_code' field has been set */
    public boolean hasShippingCarrierCode() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'shipping_carrier_code' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder clearShippingCarrierCode() {
      shipping_carrier_code = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'shipping_company' field */
    public java.lang.CharSequence getShippingCompany() {
      return shipping_company;
    }
    
    /** Sets the value of the 'shipping_company' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder setShippingCompany( java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.shipping_company = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'shipping_company' field has been set */
    public boolean hasShippingCompany() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'shipping_company' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder clearShippingCompany() {
      shipping_company = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'shipping_tracking' field */
    public java.lang.CharSequence getShippingTracking() {
      return shipping_tracking;
    }
    
    /** Sets the value of the 'shipping_tracking' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder setShippingTracking( java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.shipping_tracking = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'shipping_tracking' field has been set */
    public boolean hasShippingTracking() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'shipping_tracking' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder clearShippingTracking() {
      shipping_tracking = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'shipping_tracking_url' field */
    public java.lang.CharSequence getShippingTrackingUrl() {
      return shipping_tracking_url;
    }
    
    /** Sets the value of the 'shipping_tracking_url' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder setShippingTrackingUrl( java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.shipping_tracking_url = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'shipping_tracking_url' field has been set */
    public boolean hasShippingTrackingUrl() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'shipping_tracking_url' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder clearShippingTrackingUrl() {
      shipping_tracking_url = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'delivery_date' field */
    public java.lang.Long getDeliveryDate() {
      return delivery_date;
    }
    
    /** Sets the value of the 'delivery_date' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder setDeliveryDate( java.lang.Long value) {
      validate(fields()[9], value);
      this.delivery_date = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'delivery_date' field has been set */
    public boolean hasDeliveryDate() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'delivery_date' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder clearDeliveryDate() {
      delivery_date = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'invoice_access_key' field */
    public java.lang.CharSequence getInvoiceAccessKey() {
      return invoice_access_key;
    }
    
    /** Sets the value of the 'invoice_access_key' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder setInvoiceAccessKey( java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.invoice_access_key = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'invoice_access_key' field has been set */
    public boolean hasInvoiceAccessKey() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'invoice_access_key' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder clearInvoiceAccessKey() {
      invoice_access_key = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'invoice_date' field */
    public java.lang.Long getInvoiceDate() {
      return invoice_date;
    }
    
    /** Sets the value of the 'invoice_date' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder setInvoiceDate( java.lang.Long value) {
      validate(fields()[11], value);
      this.invoice_date = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'invoice_date' field has been set */
    public boolean hasInvoiceDate() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'invoice_date' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder clearInvoiceDate() {
      invoice_date = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'invoice_line' field */
    public java.lang.CharSequence getInvoiceLine() {
      return invoice_line;
    }
    
    /** Sets the value of the 'invoice_line' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder setInvoiceLine( java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.invoice_line = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'invoice_line' field has been set */
    public boolean hasInvoiceLine() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'invoice_line' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder clearInvoiceLine() {
      invoice_line = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'invoice_number' field */
    public java.lang.CharSequence getInvoiceNumber() {
      return invoice_number;
    }
    
    /** Sets the value of the 'invoice_number' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder setInvoiceNumber( java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.invoice_number = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'invoice_number' field has been set */
    public boolean hasInvoiceNumber() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'invoice_number' field */
    public br.com.hitbra.marketplace.avro.orders.Order.Builder clearInvoiceNumber() {
      invoice_number = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    @Override
    public Order build() {
      try {
        Order record = new Order();
        record.commercial_id = fieldSetFlags()[0] ? this.commercial_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.order_id = fieldSetFlags()[1] ? this.order_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.order_state = fieldSetFlags()[2] ? this.order_state : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.shop_id = fieldSetFlags()[3] ? this.shop_id : (java.lang.Long) defaultValue(fields()[3]);
        record.order_lines = fieldSetFlags()[4] ? this.order_lines : (java.util.List<br.com.hitbra.marketplace.avro.orders.OrderLine>) defaultValue(fields()[4]);
        record.shipping_carrier_code = fieldSetFlags()[5] ? this.shipping_carrier_code : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.shipping_company = fieldSetFlags()[6] ? this.shipping_company : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.shipping_tracking = fieldSetFlags()[7] ? this.shipping_tracking : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.shipping_tracking_url = fieldSetFlags()[8] ? this.shipping_tracking_url : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.delivery_date = fieldSetFlags()[9] ? this.delivery_date : (java.lang.Long) defaultValue(fields()[9]);
        record.invoice_access_key = fieldSetFlags()[10] ? this.invoice_access_key : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.invoice_date = fieldSetFlags()[11] ? this.invoice_date : (java.lang.Long) defaultValue(fields()[11]);
        record.invoice_line = fieldSetFlags()[12] ? this.invoice_line : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.invoice_number = fieldSetFlags()[13] ? this.invoice_number : (java.lang.CharSequence) defaultValue(fields()[13]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
