/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package br.com.hitbra.marketplace.offer.outbound;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class OfferOutbound extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OfferOutbound\",\"namespace\":\"br.com.hitbra.marketplace.offer.outbound\",\"fields\":[{\"name\":\"OFFER_ID\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"OFFER_ID_STRING\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"ACTIVE\",\"type\":[\"null\",\"boolean\"],\"default\":null},{\"name\":\"DELETED\",\"type\":[\"null\",\"boolean\"],\"default\":null},{\"name\":\"SHOP_ID\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"PRODUCT_SKU\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"SHOP_SKU\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"PRICE\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"ORIGIN_PRICE\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"QUANTITY\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"LEADTIME_TO_SHIP\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"DISCOUNT_START_DATE\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"DISCOUNT_END_DATE\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"AVAILABLE_START_DATE\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"AVAILABLE_END_DATE\",\"type\":[\"null\",\"long\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.Long OFFER_ID;
  @Deprecated public java.lang.CharSequence OFFER_ID_STRING;
  @Deprecated public java.lang.Boolean ACTIVE;
  @Deprecated public java.lang.Boolean DELETED;
  @Deprecated public java.lang.Long SHOP_ID;
  @Deprecated public java.lang.CharSequence PRODUCT_SKU;
  @Deprecated public java.lang.CharSequence SHOP_SKU;
  @Deprecated public java.lang.Double PRICE;
  @Deprecated public java.lang.Double ORIGIN_PRICE;
  @Deprecated public java.lang.Integer QUANTITY;
  @Deprecated public java.lang.Integer LEADTIME_TO_SHIP;
  @Deprecated public java.lang.Long DISCOUNT_START_DATE;
  @Deprecated public java.lang.Long DISCOUNT_END_DATE;
  @Deprecated public java.lang.Long AVAILABLE_START_DATE;
  @Deprecated public java.lang.Long AVAILABLE_END_DATE;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public OfferOutbound() {}

  /**
   * All-args constructor.
   */
  public OfferOutbound(java.lang.Long OFFER_ID, java.lang.CharSequence OFFER_ID_STRING, java.lang.Boolean ACTIVE, java.lang.Boolean DELETED, java.lang.Long SHOP_ID, java.lang.CharSequence PRODUCT_SKU, java.lang.CharSequence SHOP_SKU, java.lang.Double PRICE, java.lang.Double ORIGIN_PRICE, java.lang.Integer QUANTITY, java.lang.Integer LEADTIME_TO_SHIP, java.lang.Long DISCOUNT_START_DATE, java.lang.Long DISCOUNT_END_DATE, java.lang.Long AVAILABLE_START_DATE, java.lang.Long AVAILABLE_END_DATE) {
    this.OFFER_ID = OFFER_ID;
    this.OFFER_ID_STRING = OFFER_ID_STRING;
    this.ACTIVE = ACTIVE;
    this.DELETED = DELETED;
    this.SHOP_ID = SHOP_ID;
    this.PRODUCT_SKU = PRODUCT_SKU;
    this.SHOP_SKU = SHOP_SKU;
    this.PRICE = PRICE;
    this.ORIGIN_PRICE = ORIGIN_PRICE;
    this.QUANTITY = QUANTITY;
    this.LEADTIME_TO_SHIP = LEADTIME_TO_SHIP;
    this.DISCOUNT_START_DATE = DISCOUNT_START_DATE;
    this.DISCOUNT_END_DATE = DISCOUNT_END_DATE;
    this.AVAILABLE_START_DATE = AVAILABLE_START_DATE;
    this.AVAILABLE_END_DATE = AVAILABLE_END_DATE;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return OFFER_ID;
    case 1: return OFFER_ID_STRING;
    case 2: return ACTIVE;
    case 3: return DELETED;
    case 4: return SHOP_ID;
    case 5: return PRODUCT_SKU;
    case 6: return SHOP_SKU;
    case 7: return PRICE;
    case 8: return ORIGIN_PRICE;
    case 9: return QUANTITY;
    case 10: return LEADTIME_TO_SHIP;
    case 11: return DISCOUNT_START_DATE;
    case 12: return DISCOUNT_END_DATE;
    case 13: return AVAILABLE_START_DATE;
    case 14: return AVAILABLE_END_DATE;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: OFFER_ID = (java.lang.Long)value$; break;
    case 1: OFFER_ID_STRING = (java.lang.CharSequence)value$; break;
    case 2: ACTIVE = (java.lang.Boolean)value$; break;
    case 3: DELETED = (java.lang.Boolean)value$; break;
    case 4: SHOP_ID = (java.lang.Long)value$; break;
    case 5: PRODUCT_SKU = (java.lang.CharSequence)value$; break;
    case 6: SHOP_SKU = (java.lang.CharSequence)value$; break;
    case 7: PRICE = (java.lang.Double)value$; break;
    case 8: ORIGIN_PRICE = (java.lang.Double)value$; break;
    case 9: QUANTITY = (java.lang.Integer)value$; break;
    case 10: LEADTIME_TO_SHIP = (java.lang.Integer)value$; break;
    case 11: DISCOUNT_START_DATE = (java.lang.Long)value$; break;
    case 12: DISCOUNT_END_DATE = (java.lang.Long)value$; break;
    case 13: AVAILABLE_START_DATE = (java.lang.Long)value$; break;
    case 14: AVAILABLE_END_DATE = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'OFFER_ID' field.
   */
  public java.lang.Long getOFFERID() {
    return OFFER_ID;
  }

  /**
   * Sets the value of the 'OFFER_ID' field.
   * @param value the value to set.
   */
  public void setOFFERID(java.lang.Long value) {
    this.OFFER_ID = value;
  }

  /**
   * Gets the value of the 'OFFER_ID_STRING' field.
   */
  public java.lang.CharSequence getOFFERIDSTRING() {
    return OFFER_ID_STRING;
  }

  /**
   * Sets the value of the 'OFFER_ID_STRING' field.
   * @param value the value to set.
   */
  public void setOFFERIDSTRING(java.lang.CharSequence value) {
    this.OFFER_ID_STRING = value;
  }

  /**
   * Gets the value of the 'ACTIVE' field.
   */
  public java.lang.Boolean getACTIVE() {
    return ACTIVE;
  }

  /**
   * Sets the value of the 'ACTIVE' field.
   * @param value the value to set.
   */
  public void setACTIVE(java.lang.Boolean value) {
    this.ACTIVE = value;
  }

  /**
   * Gets the value of the 'DELETED' field.
   */
  public java.lang.Boolean getDELETED() {
    return DELETED;
  }

  /**
   * Sets the value of the 'DELETED' field.
   * @param value the value to set.
   */
  public void setDELETED(java.lang.Boolean value) {
    this.DELETED = value;
  }

  /**
   * Gets the value of the 'SHOP_ID' field.
   */
  public java.lang.Long getSHOPID() {
    return SHOP_ID;
  }

  /**
   * Sets the value of the 'SHOP_ID' field.
   * @param value the value to set.
   */
  public void setSHOPID(java.lang.Long value) {
    this.SHOP_ID = value;
  }

  /**
   * Gets the value of the 'PRODUCT_SKU' field.
   */
  public java.lang.CharSequence getPRODUCTSKU() {
    return PRODUCT_SKU;
  }

  /**
   * Sets the value of the 'PRODUCT_SKU' field.
   * @param value the value to set.
   */
  public void setPRODUCTSKU(java.lang.CharSequence value) {
    this.PRODUCT_SKU = value;
  }

  /**
   * Gets the value of the 'SHOP_SKU' field.
   */
  public java.lang.CharSequence getSHOPSKU() {
    return SHOP_SKU;
  }

  /**
   * Sets the value of the 'SHOP_SKU' field.
   * @param value the value to set.
   */
  public void setSHOPSKU(java.lang.CharSequence value) {
    this.SHOP_SKU = value;
  }

  /**
   * Gets the value of the 'PRICE' field.
   */
  public java.lang.Double getPRICE() {
    return PRICE;
  }

  /**
   * Sets the value of the 'PRICE' field.
   * @param value the value to set.
   */
  public void setPRICE(java.lang.Double value) {
    this.PRICE = value;
  }

  /**
   * Gets the value of the 'ORIGIN_PRICE' field.
   */
  public java.lang.Double getORIGINPRICE() {
    return ORIGIN_PRICE;
  }

  /**
   * Sets the value of the 'ORIGIN_PRICE' field.
   * @param value the value to set.
   */
  public void setORIGINPRICE(java.lang.Double value) {
    this.ORIGIN_PRICE = value;
  }

  /**
   * Gets the value of the 'QUANTITY' field.
   */
  public java.lang.Integer getQUANTITY() {
    return QUANTITY;
  }

  /**
   * Sets the value of the 'QUANTITY' field.
   * @param value the value to set.
   */
  public void setQUANTITY(java.lang.Integer value) {
    this.QUANTITY = value;
  }

  /**
   * Gets the value of the 'LEADTIME_TO_SHIP' field.
   */
  public java.lang.Integer getLEADTIMETOSHIP() {
    return LEADTIME_TO_SHIP;
  }

  /**
   * Sets the value of the 'LEADTIME_TO_SHIP' field.
   * @param value the value to set.
   */
  public void setLEADTIMETOSHIP(java.lang.Integer value) {
    this.LEADTIME_TO_SHIP = value;
  }

  /**
   * Gets the value of the 'DISCOUNT_START_DATE' field.
   */
  public java.lang.Long getDISCOUNTSTARTDATE() {
    return DISCOUNT_START_DATE;
  }

  /**
   * Sets the value of the 'DISCOUNT_START_DATE' field.
   * @param value the value to set.
   */
  public void setDISCOUNTSTARTDATE(java.lang.Long value) {
    this.DISCOUNT_START_DATE = value;
  }

  /**
   * Gets the value of the 'DISCOUNT_END_DATE' field.
   */
  public java.lang.Long getDISCOUNTENDDATE() {
    return DISCOUNT_END_DATE;
  }

  /**
   * Sets the value of the 'DISCOUNT_END_DATE' field.
   * @param value the value to set.
   */
  public void setDISCOUNTENDDATE(java.lang.Long value) {
    this.DISCOUNT_END_DATE = value;
  }

  /**
   * Gets the value of the 'AVAILABLE_START_DATE' field.
   */
  public java.lang.Long getAVAILABLESTARTDATE() {
    return AVAILABLE_START_DATE;
  }

  /**
   * Sets the value of the 'AVAILABLE_START_DATE' field.
   * @param value the value to set.
   */
  public void setAVAILABLESTARTDATE(java.lang.Long value) {
    this.AVAILABLE_START_DATE = value;
  }

  /**
   * Gets the value of the 'AVAILABLE_END_DATE' field.
   */
  public java.lang.Long getAVAILABLEENDDATE() {
    return AVAILABLE_END_DATE;
  }

  /**
   * Sets the value of the 'AVAILABLE_END_DATE' field.
   * @param value the value to set.
   */
  public void setAVAILABLEENDDATE(java.lang.Long value) {
    this.AVAILABLE_END_DATE = value;
  }

  /** Creates a new OfferOutbound RecordBuilder */
  public static br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder newBuilder() {
    return new br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder();
  }
  
  /** Creates a new OfferOutbound RecordBuilder by copying an existing Builder */
  public static br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder newBuilder( br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder other) {
    return new br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder(other);
  }
  
  /** Creates a new OfferOutbound RecordBuilder by copying an existing OfferOutbound instance */
  public static br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder newBuilder( br.com.hitbra.marketplace.offer.outbound.OfferOutbound other) {
    return new br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder(other);
  }
  
  /**
   * RecordBuilder for OfferOutbound instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OfferOutbound>
    implements org.apache.avro.data.RecordBuilder<OfferOutbound> {

    private java.lang.Long OFFER_ID;
    private java.lang.CharSequence OFFER_ID_STRING;
    private java.lang.Boolean ACTIVE;
    private java.lang.Boolean DELETED;
    private java.lang.Long SHOP_ID;
    private java.lang.CharSequence PRODUCT_SKU;
    private java.lang.CharSequence SHOP_SKU;
    private java.lang.Double PRICE;
    private java.lang.Double ORIGIN_PRICE;
    private java.lang.Integer QUANTITY;
    private java.lang.Integer LEADTIME_TO_SHIP;
    private java.lang.Long DISCOUNT_START_DATE;
    private java.lang.Long DISCOUNT_END_DATE;
    private java.lang.Long AVAILABLE_START_DATE;
    private java.lang.Long AVAILABLE_END_DATE;

    /** Creates a new Builder */
    private Builder() {
      super(br.com.hitbra.marketplace.offer.outbound.OfferOutbound.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.OFFER_ID)) {
        this.OFFER_ID = data().deepCopy(fields()[0].schema(), other.OFFER_ID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.OFFER_ID_STRING)) {
        this.OFFER_ID_STRING = data().deepCopy(fields()[1].schema(), other.OFFER_ID_STRING);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ACTIVE)) {
        this.ACTIVE = data().deepCopy(fields()[2].schema(), other.ACTIVE);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.DELETED)) {
        this.DELETED = data().deepCopy(fields()[3].schema(), other.DELETED);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.SHOP_ID)) {
        this.SHOP_ID = data().deepCopy(fields()[4].schema(), other.SHOP_ID);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.PRODUCT_SKU)) {
        this.PRODUCT_SKU = data().deepCopy(fields()[5].schema(), other.PRODUCT_SKU);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.SHOP_SKU)) {
        this.SHOP_SKU = data().deepCopy(fields()[6].schema(), other.SHOP_SKU);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.PRICE)) {
        this.PRICE = data().deepCopy(fields()[7].schema(), other.PRICE);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.ORIGIN_PRICE)) {
        this.ORIGIN_PRICE = data().deepCopy(fields()[8].schema(), other.ORIGIN_PRICE);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.QUANTITY)) {
        this.QUANTITY = data().deepCopy(fields()[9].schema(), other.QUANTITY);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.LEADTIME_TO_SHIP)) {
        this.LEADTIME_TO_SHIP = data().deepCopy(fields()[10].schema(), other.LEADTIME_TO_SHIP);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.DISCOUNT_START_DATE)) {
        this.DISCOUNT_START_DATE = data().deepCopy(fields()[11].schema(), other.DISCOUNT_START_DATE);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.DISCOUNT_END_DATE)) {
        this.DISCOUNT_END_DATE = data().deepCopy(fields()[12].schema(), other.DISCOUNT_END_DATE);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.AVAILABLE_START_DATE)) {
        this.AVAILABLE_START_DATE = data().deepCopy(fields()[13].schema(), other.AVAILABLE_START_DATE);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.AVAILABLE_END_DATE)) {
        this.AVAILABLE_END_DATE = data().deepCopy(fields()[14].schema(), other.AVAILABLE_END_DATE);
        fieldSetFlags()[14] = true;
      }
    }
    
    /** Creates a Builder by copying an existing OfferOutbound instance */
    private Builder(br.com.hitbra.marketplace.offer.outbound.OfferOutbound other) {
            super(br.com.hitbra.marketplace.offer.outbound.OfferOutbound.SCHEMA$);
      if (isValidValue(fields()[0], other.OFFER_ID)) {
        this.OFFER_ID = data().deepCopy(fields()[0].schema(), other.OFFER_ID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.OFFER_ID_STRING)) {
        this.OFFER_ID_STRING = data().deepCopy(fields()[1].schema(), other.OFFER_ID_STRING);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ACTIVE)) {
        this.ACTIVE = data().deepCopy(fields()[2].schema(), other.ACTIVE);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.DELETED)) {
        this.DELETED = data().deepCopy(fields()[3].schema(), other.DELETED);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.SHOP_ID)) {
        this.SHOP_ID = data().deepCopy(fields()[4].schema(), other.SHOP_ID);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.PRODUCT_SKU)) {
        this.PRODUCT_SKU = data().deepCopy(fields()[5].schema(), other.PRODUCT_SKU);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.SHOP_SKU)) {
        this.SHOP_SKU = data().deepCopy(fields()[6].schema(), other.SHOP_SKU);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.PRICE)) {
        this.PRICE = data().deepCopy(fields()[7].schema(), other.PRICE);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.ORIGIN_PRICE)) {
        this.ORIGIN_PRICE = data().deepCopy(fields()[8].schema(), other.ORIGIN_PRICE);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.QUANTITY)) {
        this.QUANTITY = data().deepCopy(fields()[9].schema(), other.QUANTITY);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.LEADTIME_TO_SHIP)) {
        this.LEADTIME_TO_SHIP = data().deepCopy(fields()[10].schema(), other.LEADTIME_TO_SHIP);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.DISCOUNT_START_DATE)) {
        this.DISCOUNT_START_DATE = data().deepCopy(fields()[11].schema(), other.DISCOUNT_START_DATE);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.DISCOUNT_END_DATE)) {
        this.DISCOUNT_END_DATE = data().deepCopy(fields()[12].schema(), other.DISCOUNT_END_DATE);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.AVAILABLE_START_DATE)) {
        this.AVAILABLE_START_DATE = data().deepCopy(fields()[13].schema(), other.AVAILABLE_START_DATE);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.AVAILABLE_END_DATE)) {
        this.AVAILABLE_END_DATE = data().deepCopy(fields()[14].schema(), other.AVAILABLE_END_DATE);
        fieldSetFlags()[14] = true;
      }
    }

    /** Gets the value of the 'OFFER_ID' field */
    public java.lang.Long getOFFERID() {
      return OFFER_ID;
    }
    
    /** Sets the value of the 'OFFER_ID' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder setOFFERID( java.lang.Long value) {
      validate(fields()[0], value);
      this.OFFER_ID = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'OFFER_ID' field has been set */
    public boolean hasOFFERID() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'OFFER_ID' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder clearOFFERID() {
      OFFER_ID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'OFFER_ID_STRING' field */
    public java.lang.CharSequence getOFFERIDSTRING() {
      return OFFER_ID_STRING;
    }
    
    /** Sets the value of the 'OFFER_ID_STRING' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder setOFFERIDSTRING( java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.OFFER_ID_STRING = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'OFFER_ID_STRING' field has been set */
    public boolean hasOFFERIDSTRING() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'OFFER_ID_STRING' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder clearOFFERIDSTRING() {
      OFFER_ID_STRING = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'ACTIVE' field */
    public java.lang.Boolean getACTIVE() {
      return ACTIVE;
    }
    
    /** Sets the value of the 'ACTIVE' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder setACTIVE( java.lang.Boolean value) {
      validate(fields()[2], value);
      this.ACTIVE = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'ACTIVE' field has been set */
    public boolean hasACTIVE() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'ACTIVE' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder clearACTIVE() {
      ACTIVE = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'DELETED' field */
    public java.lang.Boolean getDELETED() {
      return DELETED;
    }
    
    /** Sets the value of the 'DELETED' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder setDELETED( java.lang.Boolean value) {
      validate(fields()[3], value);
      this.DELETED = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'DELETED' field has been set */
    public boolean hasDELETED() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'DELETED' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder clearDELETED() {
      DELETED = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'SHOP_ID' field */
    public java.lang.Long getSHOPID() {
      return SHOP_ID;
    }
    
    /** Sets the value of the 'SHOP_ID' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder setSHOPID( java.lang.Long value) {
      validate(fields()[4], value);
      this.SHOP_ID = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'SHOP_ID' field has been set */
    public boolean hasSHOPID() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'SHOP_ID' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder clearSHOPID() {
      SHOP_ID = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'PRODUCT_SKU' field */
    public java.lang.CharSequence getPRODUCTSKU() {
      return PRODUCT_SKU;
    }
    
    /** Sets the value of the 'PRODUCT_SKU' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder setPRODUCTSKU( java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.PRODUCT_SKU = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'PRODUCT_SKU' field has been set */
    public boolean hasPRODUCTSKU() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'PRODUCT_SKU' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder clearPRODUCTSKU() {
      PRODUCT_SKU = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'SHOP_SKU' field */
    public java.lang.CharSequence getSHOPSKU() {
      return SHOP_SKU;
    }
    
    /** Sets the value of the 'SHOP_SKU' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder setSHOPSKU( java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.SHOP_SKU = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'SHOP_SKU' field has been set */
    public boolean hasSHOPSKU() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'SHOP_SKU' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder clearSHOPSKU() {
      SHOP_SKU = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'PRICE' field */
    public java.lang.Double getPRICE() {
      return PRICE;
    }
    
    /** Sets the value of the 'PRICE' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder setPRICE( java.lang.Double value) {
      validate(fields()[7], value);
      this.PRICE = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'PRICE' field has been set */
    public boolean hasPRICE() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'PRICE' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder clearPRICE() {
      PRICE = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'ORIGIN_PRICE' field */
    public java.lang.Double getORIGINPRICE() {
      return ORIGIN_PRICE;
    }
    
    /** Sets the value of the 'ORIGIN_PRICE' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder setORIGINPRICE( java.lang.Double value) {
      validate(fields()[8], value);
      this.ORIGIN_PRICE = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'ORIGIN_PRICE' field has been set */
    public boolean hasORIGINPRICE() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'ORIGIN_PRICE' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder clearORIGINPRICE() {
      ORIGIN_PRICE = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'QUANTITY' field */
    public java.lang.Integer getQUANTITY() {
      return QUANTITY;
    }
    
    /** Sets the value of the 'QUANTITY' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder setQUANTITY( java.lang.Integer value) {
      validate(fields()[9], value);
      this.QUANTITY = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'QUANTITY' field has been set */
    public boolean hasQUANTITY() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'QUANTITY' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder clearQUANTITY() {
      QUANTITY = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'LEADTIME_TO_SHIP' field */
    public java.lang.Integer getLEADTIMETOSHIP() {
      return LEADTIME_TO_SHIP;
    }
    
    /** Sets the value of the 'LEADTIME_TO_SHIP' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder setLEADTIMETOSHIP( java.lang.Integer value) {
      validate(fields()[10], value);
      this.LEADTIME_TO_SHIP = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'LEADTIME_TO_SHIP' field has been set */
    public boolean hasLEADTIMETOSHIP() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'LEADTIME_TO_SHIP' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder clearLEADTIMETOSHIP() {
      LEADTIME_TO_SHIP = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'DISCOUNT_START_DATE' field */
    public java.lang.Long getDISCOUNTSTARTDATE() {
      return DISCOUNT_START_DATE;
    }
    
    /** Sets the value of the 'DISCOUNT_START_DATE' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder setDISCOUNTSTARTDATE( java.lang.Long value) {
      validate(fields()[11], value);
      this.DISCOUNT_START_DATE = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'DISCOUNT_START_DATE' field has been set */
    public boolean hasDISCOUNTSTARTDATE() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'DISCOUNT_START_DATE' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder clearDISCOUNTSTARTDATE() {
      DISCOUNT_START_DATE = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'DISCOUNT_END_DATE' field */
    public java.lang.Long getDISCOUNTENDDATE() {
      return DISCOUNT_END_DATE;
    }
    
    /** Sets the value of the 'DISCOUNT_END_DATE' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder setDISCOUNTENDDATE( java.lang.Long value) {
      validate(fields()[12], value);
      this.DISCOUNT_END_DATE = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'DISCOUNT_END_DATE' field has been set */
    public boolean hasDISCOUNTENDDATE() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'DISCOUNT_END_DATE' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder clearDISCOUNTENDDATE() {
      DISCOUNT_END_DATE = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'AVAILABLE_START_DATE' field */
    public java.lang.Long getAVAILABLESTARTDATE() {
      return AVAILABLE_START_DATE;
    }
    
    /** Sets the value of the 'AVAILABLE_START_DATE' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder setAVAILABLESTARTDATE( java.lang.Long value) {
      validate(fields()[13], value);
      this.AVAILABLE_START_DATE = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'AVAILABLE_START_DATE' field has been set */
    public boolean hasAVAILABLESTARTDATE() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'AVAILABLE_START_DATE' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder clearAVAILABLESTARTDATE() {
      AVAILABLE_START_DATE = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'AVAILABLE_END_DATE' field */
    public java.lang.Long getAVAILABLEENDDATE() {
      return AVAILABLE_END_DATE;
    }
    
    /** Sets the value of the 'AVAILABLE_END_DATE' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder setAVAILABLEENDDATE( java.lang.Long value) {
      validate(fields()[14], value);
      this.AVAILABLE_END_DATE = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'AVAILABLE_END_DATE' field has been set */
    public boolean hasAVAILABLEENDDATE() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'AVAILABLE_END_DATE' field */
    public br.com.hitbra.marketplace.offer.outbound.OfferOutbound.Builder clearAVAILABLEENDDATE() {
      AVAILABLE_END_DATE = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    @Override
    public OfferOutbound build() {
      try {
        OfferOutbound record = new OfferOutbound();
        record.OFFER_ID = fieldSetFlags()[0] ? this.OFFER_ID : (java.lang.Long) defaultValue(fields()[0]);
        record.OFFER_ID_STRING = fieldSetFlags()[1] ? this.OFFER_ID_STRING : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.ACTIVE = fieldSetFlags()[2] ? this.ACTIVE : (java.lang.Boolean) defaultValue(fields()[2]);
        record.DELETED = fieldSetFlags()[3] ? this.DELETED : (java.lang.Boolean) defaultValue(fields()[3]);
        record.SHOP_ID = fieldSetFlags()[4] ? this.SHOP_ID : (java.lang.Long) defaultValue(fields()[4]);
        record.PRODUCT_SKU = fieldSetFlags()[5] ? this.PRODUCT_SKU : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.SHOP_SKU = fieldSetFlags()[6] ? this.SHOP_SKU : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.PRICE = fieldSetFlags()[7] ? this.PRICE : (java.lang.Double) defaultValue(fields()[7]);
        record.ORIGIN_PRICE = fieldSetFlags()[8] ? this.ORIGIN_PRICE : (java.lang.Double) defaultValue(fields()[8]);
        record.QUANTITY = fieldSetFlags()[9] ? this.QUANTITY : (java.lang.Integer) defaultValue(fields()[9]);
        record.LEADTIME_TO_SHIP = fieldSetFlags()[10] ? this.LEADTIME_TO_SHIP : (java.lang.Integer) defaultValue(fields()[10]);
        record.DISCOUNT_START_DATE = fieldSetFlags()[11] ? this.DISCOUNT_START_DATE : (java.lang.Long) defaultValue(fields()[11]);
        record.DISCOUNT_END_DATE = fieldSetFlags()[12] ? this.DISCOUNT_END_DATE : (java.lang.Long) defaultValue(fields()[12]);
        record.AVAILABLE_START_DATE = fieldSetFlags()[13] ? this.AVAILABLE_START_DATE : (java.lang.Long) defaultValue(fields()[13]);
        record.AVAILABLE_END_DATE = fieldSetFlags()[14] ? this.AVAILABLE_END_DATE : (java.lang.Long) defaultValue(fields()[14]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
