/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package br.com.hitbra.marketplace.avro.shops;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ProDetails extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProDetails\",\"namespace\":\"br.com.hitbra.marketplace.avro.shops\",\"fields\":[{\"name\":\"corporate_name\",\"type\":[\"string\",\"null\"]},{\"name\":\"identification_number\",\"type\":[\"string\",\"null\"]},{\"name\":\"tax_identification_number\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence corporate_name;
  @Deprecated public java.lang.CharSequence identification_number;
  @Deprecated public java.lang.CharSequence tax_identification_number;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ProDetails() {}

  /**
   * All-args constructor.
   */
  public ProDetails(java.lang.CharSequence corporate_name, java.lang.CharSequence identification_number, java.lang.CharSequence tax_identification_number) {
    this.corporate_name = corporate_name;
    this.identification_number = identification_number;
    this.tax_identification_number = tax_identification_number;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return corporate_name;
    case 1: return identification_number;
    case 2: return tax_identification_number;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: corporate_name = (java.lang.CharSequence)value$; break;
    case 1: identification_number = (java.lang.CharSequence)value$; break;
    case 2: tax_identification_number = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'corporate_name' field.
   */
  public java.lang.CharSequence getCorporateName() {
    return corporate_name;
  }

  /**
   * Sets the value of the 'corporate_name' field.
   * @param value the value to set.
   */
  public void setCorporateName(java.lang.CharSequence value) {
    this.corporate_name = value;
  }

  /**
   * Gets the value of the 'identification_number' field.
   */
  public java.lang.CharSequence getIdentificationNumber() {
    return identification_number;
  }

  /**
   * Sets the value of the 'identification_number' field.
   * @param value the value to set.
   */
  public void setIdentificationNumber(java.lang.CharSequence value) {
    this.identification_number = value;
  }

  /**
   * Gets the value of the 'tax_identification_number' field.
   */
  public java.lang.CharSequence getTaxIdentificationNumber() {
    return tax_identification_number;
  }

  /**
   * Sets the value of the 'tax_identification_number' field.
   * @param value the value to set.
   */
  public void setTaxIdentificationNumber(java.lang.CharSequence value) {
    this.tax_identification_number = value;
  }

  /** Creates a new ProDetails RecordBuilder */
  public static br.com.hitbra.marketplace.avro.shops.ProDetails.Builder newBuilder() {
    return new br.com.hitbra.marketplace.avro.shops.ProDetails.Builder();
  }
  
  /** Creates a new ProDetails RecordBuilder by copying an existing Builder */
  public static br.com.hitbra.marketplace.avro.shops.ProDetails.Builder newBuilder( br.com.hitbra.marketplace.avro.shops.ProDetails.Builder other) {
    return new br.com.hitbra.marketplace.avro.shops.ProDetails.Builder(other);
  }
  
  /** Creates a new ProDetails RecordBuilder by copying an existing ProDetails instance */
  public static br.com.hitbra.marketplace.avro.shops.ProDetails.Builder newBuilder( br.com.hitbra.marketplace.avro.shops.ProDetails other) {
    return new br.com.hitbra.marketplace.avro.shops.ProDetails.Builder(other);
  }
  
  /**
   * RecordBuilder for ProDetails instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProDetails>
    implements org.apache.avro.data.RecordBuilder<ProDetails> {

    private java.lang.CharSequence corporate_name;
    private java.lang.CharSequence identification_number;
    private java.lang.CharSequence tax_identification_number;

    /** Creates a new Builder */
    private Builder() {
      super(br.com.hitbra.marketplace.avro.shops.ProDetails.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(br.com.hitbra.marketplace.avro.shops.ProDetails.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.corporate_name)) {
        this.corporate_name = data().deepCopy(fields()[0].schema(), other.corporate_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.identification_number)) {
        this.identification_number = data().deepCopy(fields()[1].schema(), other.identification_number);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tax_identification_number)) {
        this.tax_identification_number = data().deepCopy(fields()[2].schema(), other.tax_identification_number);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ProDetails instance */
    private Builder(br.com.hitbra.marketplace.avro.shops.ProDetails other) {
            super(br.com.hitbra.marketplace.avro.shops.ProDetails.SCHEMA$);
      if (isValidValue(fields()[0], other.corporate_name)) {
        this.corporate_name = data().deepCopy(fields()[0].schema(), other.corporate_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.identification_number)) {
        this.identification_number = data().deepCopy(fields()[1].schema(), other.identification_number);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.tax_identification_number)) {
        this.tax_identification_number = data().deepCopy(fields()[2].schema(), other.tax_identification_number);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'corporate_name' field */
    public java.lang.CharSequence getCorporateName() {
      return corporate_name;
    }
    
    /** Sets the value of the 'corporate_name' field */
    public br.com.hitbra.marketplace.avro.shops.ProDetails.Builder setCorporateName( java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.corporate_name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'corporate_name' field has been set */
    public boolean hasCorporateName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'corporate_name' field */
    public br.com.hitbra.marketplace.avro.shops.ProDetails.Builder clearCorporateName() {
      corporate_name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'identification_number' field */
    public java.lang.CharSequence getIdentificationNumber() {
      return identification_number;
    }
    
    /** Sets the value of the 'identification_number' field */
    public br.com.hitbra.marketplace.avro.shops.ProDetails.Builder setIdentificationNumber( java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.identification_number = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'identification_number' field has been set */
    public boolean hasIdentificationNumber() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'identification_number' field */
    public br.com.hitbra.marketplace.avro.shops.ProDetails.Builder clearIdentificationNumber() {
      identification_number = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'tax_identification_number' field */
    public java.lang.CharSequence getTaxIdentificationNumber() {
      return tax_identification_number;
    }
    
    /** Sets the value of the 'tax_identification_number' field */
    public br.com.hitbra.marketplace.avro.shops.ProDetails.Builder setTaxIdentificationNumber( java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.tax_identification_number = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'tax_identification_number' field has been set */
    public boolean hasTaxIdentificationNumber() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'tax_identification_number' field */
    public br.com.hitbra.marketplace.avro.shops.ProDetails.Builder clearTaxIdentificationNumber() {
      tax_identification_number = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public ProDetails build() {
      try {
        ProDetails record = new ProDetails();
        record.corporate_name = fieldSetFlags()[0] ? this.corporate_name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.identification_number = fieldSetFlags()[1] ? this.identification_number : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.tax_identification_number = fieldSetFlags()[2] ? this.tax_identification_number : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
