/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package br.com.hitbra.marketplace.avro.shops;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ShopState { 
  OPEN, CLOSE, SUSPENDED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ShopState\",\"namespace\":\"br.com.hitbra.marketplace.avro.shops\",\"symbols\":[\"OPEN\",\"CLOSE\",\"SUSPENDED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
