/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.ksql.avro_schemas;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class KsqlDataSourceSchema_CONTACT_INFORMATIONS extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"KsqlDataSourceSchema_CONTACT_INFORMATIONS\",\"namespace\":\"io.confluent.ksql.avro_schemas\",\"fields\":[{\"name\":\"CITY\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"CIVILITY\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"COUNTRY\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"EMAIL\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"FAX\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"FIRSTNAME\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"LASTNAME\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"PHONE\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"PHONE_SECONDARY\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"STATE\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"STREET1\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"STREET2\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"WEB_SITE\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"ZIP_CODE\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence CITY;
  @Deprecated public java.lang.CharSequence CIVILITY;
  @Deprecated public java.lang.CharSequence COUNTRY;
  @Deprecated public java.lang.CharSequence EMAIL;
  @Deprecated public java.lang.CharSequence FAX;
  @Deprecated public java.lang.CharSequence FIRSTNAME;
  @Deprecated public java.lang.CharSequence LASTNAME;
  @Deprecated public java.lang.CharSequence PHONE;
  @Deprecated public java.lang.CharSequence PHONE_SECONDARY;
  @Deprecated public java.lang.CharSequence STATE;
  @Deprecated public java.lang.CharSequence STREET1;
  @Deprecated public java.lang.CharSequence STREET2;
  @Deprecated public java.lang.CharSequence WEB_SITE;
  @Deprecated public java.lang.CharSequence ZIP_CODE;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public KsqlDataSourceSchema_CONTACT_INFORMATIONS() {}

  /**
   * All-args constructor.
   */
  public KsqlDataSourceSchema_CONTACT_INFORMATIONS(java.lang.CharSequence CITY, java.lang.CharSequence CIVILITY, java.lang.CharSequence COUNTRY, java.lang.CharSequence EMAIL, java.lang.CharSequence FAX, java.lang.CharSequence FIRSTNAME, java.lang.CharSequence LASTNAME, java.lang.CharSequence PHONE, java.lang.CharSequence PHONE_SECONDARY, java.lang.CharSequence STATE, java.lang.CharSequence STREET1, java.lang.CharSequence STREET2, java.lang.CharSequence WEB_SITE, java.lang.CharSequence ZIP_CODE) {
    this.CITY = CITY;
    this.CIVILITY = CIVILITY;
    this.COUNTRY = COUNTRY;
    this.EMAIL = EMAIL;
    this.FAX = FAX;
    this.FIRSTNAME = FIRSTNAME;
    this.LASTNAME = LASTNAME;
    this.PHONE = PHONE;
    this.PHONE_SECONDARY = PHONE_SECONDARY;
    this.STATE = STATE;
    this.STREET1 = STREET1;
    this.STREET2 = STREET2;
    this.WEB_SITE = WEB_SITE;
    this.ZIP_CODE = ZIP_CODE;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return CITY;
    case 1: return CIVILITY;
    case 2: return COUNTRY;
    case 3: return EMAIL;
    case 4: return FAX;
    case 5: return FIRSTNAME;
    case 6: return LASTNAME;
    case 7: return PHONE;
    case 8: return PHONE_SECONDARY;
    case 9: return STATE;
    case 10: return STREET1;
    case 11: return STREET2;
    case 12: return WEB_SITE;
    case 13: return ZIP_CODE;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: CITY = (java.lang.CharSequence)value$; break;
    case 1: CIVILITY = (java.lang.CharSequence)value$; break;
    case 2: COUNTRY = (java.lang.CharSequence)value$; break;
    case 3: EMAIL = (java.lang.CharSequence)value$; break;
    case 4: FAX = (java.lang.CharSequence)value$; break;
    case 5: FIRSTNAME = (java.lang.CharSequence)value$; break;
    case 6: LASTNAME = (java.lang.CharSequence)value$; break;
    case 7: PHONE = (java.lang.CharSequence)value$; break;
    case 8: PHONE_SECONDARY = (java.lang.CharSequence)value$; break;
    case 9: STATE = (java.lang.CharSequence)value$; break;
    case 10: STREET1 = (java.lang.CharSequence)value$; break;
    case 11: STREET2 = (java.lang.CharSequence)value$; break;
    case 12: WEB_SITE = (java.lang.CharSequence)value$; break;
    case 13: ZIP_CODE = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'CITY' field.
   */
  public java.lang.CharSequence getCITY() {
    return CITY;
  }

  /**
   * Sets the value of the 'CITY' field.
   * @param value the value to set.
   */
  public void setCITY(java.lang.CharSequence value) {
    this.CITY = value;
  }

  /**
   * Gets the value of the 'CIVILITY' field.
   */
  public java.lang.CharSequence getCIVILITY() {
    return CIVILITY;
  }

  /**
   * Sets the value of the 'CIVILITY' field.
   * @param value the value to set.
   */
  public void setCIVILITY(java.lang.CharSequence value) {
    this.CIVILITY = value;
  }

  /**
   * Gets the value of the 'COUNTRY' field.
   */
  public java.lang.CharSequence getCOUNTRY() {
    return COUNTRY;
  }

  /**
   * Sets the value of the 'COUNTRY' field.
   * @param value the value to set.
   */
  public void setCOUNTRY(java.lang.CharSequence value) {
    this.COUNTRY = value;
  }

  /**
   * Gets the value of the 'EMAIL' field.
   */
  public java.lang.CharSequence getEMAIL() {
    return EMAIL;
  }

  /**
   * Sets the value of the 'EMAIL' field.
   * @param value the value to set.
   */
  public void setEMAIL(java.lang.CharSequence value) {
    this.EMAIL = value;
  }

  /**
   * Gets the value of the 'FAX' field.
   */
  public java.lang.CharSequence getFAX() {
    return FAX;
  }

  /**
   * Sets the value of the 'FAX' field.
   * @param value the value to set.
   */
  public void setFAX(java.lang.CharSequence value) {
    this.FAX = value;
  }

  /**
   * Gets the value of the 'FIRSTNAME' field.
   */
  public java.lang.CharSequence getFIRSTNAME() {
    return FIRSTNAME;
  }

  /**
   * Sets the value of the 'FIRSTNAME' field.
   * @param value the value to set.
   */
  public void setFIRSTNAME(java.lang.CharSequence value) {
    this.FIRSTNAME = value;
  }

  /**
   * Gets the value of the 'LASTNAME' field.
   */
  public java.lang.CharSequence getLASTNAME() {
    return LASTNAME;
  }

  /**
   * Sets the value of the 'LASTNAME' field.
   * @param value the value to set.
   */
  public void setLASTNAME(java.lang.CharSequence value) {
    this.LASTNAME = value;
  }

  /**
   * Gets the value of the 'PHONE' field.
   */
  public java.lang.CharSequence getPHONE() {
    return PHONE;
  }

  /**
   * Sets the value of the 'PHONE' field.
   * @param value the value to set.
   */
  public void setPHONE(java.lang.CharSequence value) {
    this.PHONE = value;
  }

  /**
   * Gets the value of the 'PHONE_SECONDARY' field.
   */
  public java.lang.CharSequence getPHONESECONDARY() {
    return PHONE_SECONDARY;
  }

  /**
   * Sets the value of the 'PHONE_SECONDARY' field.
   * @param value the value to set.
   */
  public void setPHONESECONDARY(java.lang.CharSequence value) {
    this.PHONE_SECONDARY = value;
  }

  /**
   * Gets the value of the 'STATE' field.
   */
  public java.lang.CharSequence getSTATE() {
    return STATE;
  }

  /**
   * Sets the value of the 'STATE' field.
   * @param value the value to set.
   */
  public void setSTATE(java.lang.CharSequence value) {
    this.STATE = value;
  }

  /**
   * Gets the value of the 'STREET1' field.
   */
  public java.lang.CharSequence getSTREET1() {
    return STREET1;
  }

  /**
   * Sets the value of the 'STREET1' field.
   * @param value the value to set.
   */
  public void setSTREET1(java.lang.CharSequence value) {
    this.STREET1 = value;
  }

  /**
   * Gets the value of the 'STREET2' field.
   */
  public java.lang.CharSequence getSTREET2() {
    return STREET2;
  }

  /**
   * Sets the value of the 'STREET2' field.
   * @param value the value to set.
   */
  public void setSTREET2(java.lang.CharSequence value) {
    this.STREET2 = value;
  }

  /**
   * Gets the value of the 'WEB_SITE' field.
   */
  public java.lang.CharSequence getWEBSITE() {
    return WEB_SITE;
  }

  /**
   * Sets the value of the 'WEB_SITE' field.
   * @param value the value to set.
   */
  public void setWEBSITE(java.lang.CharSequence value) {
    this.WEB_SITE = value;
  }

  /**
   * Gets the value of the 'ZIP_CODE' field.
   */
  public java.lang.CharSequence getZIPCODE() {
    return ZIP_CODE;
  }

  /**
   * Sets the value of the 'ZIP_CODE' field.
   * @param value the value to set.
   */
  public void setZIPCODE(java.lang.CharSequence value) {
    this.ZIP_CODE = value;
  }

  /** Creates a new KsqlDataSourceSchema_CONTACT_INFORMATIONS RecordBuilder */
  public static io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder newBuilder() {
    return new io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder();
  }
  
  /** Creates a new KsqlDataSourceSchema_CONTACT_INFORMATIONS RecordBuilder by copying an existing Builder */
  public static io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder newBuilder(io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder other) {
    return new io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder(other);
  }
  
  /** Creates a new KsqlDataSourceSchema_CONTACT_INFORMATIONS RecordBuilder by copying an existing KsqlDataSourceSchema_CONTACT_INFORMATIONS instance */
  public static io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder newBuilder(io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS other) {
    return new io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder(other);
  }
  
  /**
   * RecordBuilder for KsqlDataSourceSchema_CONTACT_INFORMATIONS instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<KsqlDataSourceSchema_CONTACT_INFORMATIONS>
    implements org.apache.avro.data.RecordBuilder<KsqlDataSourceSchema_CONTACT_INFORMATIONS> {

    private java.lang.CharSequence CITY;
    private java.lang.CharSequence CIVILITY;
    private java.lang.CharSequence COUNTRY;
    private java.lang.CharSequence EMAIL;
    private java.lang.CharSequence FAX;
    private java.lang.CharSequence FIRSTNAME;
    private java.lang.CharSequence LASTNAME;
    private java.lang.CharSequence PHONE;
    private java.lang.CharSequence PHONE_SECONDARY;
    private java.lang.CharSequence STATE;
    private java.lang.CharSequence STREET1;
    private java.lang.CharSequence STREET2;
    private java.lang.CharSequence WEB_SITE;
    private java.lang.CharSequence ZIP_CODE;

    /** Creates a new Builder */
    private Builder() {
      super(io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.CITY)) {
        this.CITY = data().deepCopy(fields()[0].schema(), other.CITY);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.CIVILITY)) {
        this.CIVILITY = data().deepCopy(fields()[1].schema(), other.CIVILITY);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.COUNTRY)) {
        this.COUNTRY = data().deepCopy(fields()[2].schema(), other.COUNTRY);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.EMAIL)) {
        this.EMAIL = data().deepCopy(fields()[3].schema(), other.EMAIL);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.FAX)) {
        this.FAX = data().deepCopy(fields()[4].schema(), other.FAX);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.FIRSTNAME)) {
        this.FIRSTNAME = data().deepCopy(fields()[5].schema(), other.FIRSTNAME);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.LASTNAME)) {
        this.LASTNAME = data().deepCopy(fields()[6].schema(), other.LASTNAME);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.PHONE)) {
        this.PHONE = data().deepCopy(fields()[7].schema(), other.PHONE);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.PHONE_SECONDARY)) {
        this.PHONE_SECONDARY = data().deepCopy(fields()[8].schema(), other.PHONE_SECONDARY);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.STATE)) {
        this.STATE = data().deepCopy(fields()[9].schema(), other.STATE);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.STREET1)) {
        this.STREET1 = data().deepCopy(fields()[10].schema(), other.STREET1);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.STREET2)) {
        this.STREET2 = data().deepCopy(fields()[11].schema(), other.STREET2);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.WEB_SITE)) {
        this.WEB_SITE = data().deepCopy(fields()[12].schema(), other.WEB_SITE);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.ZIP_CODE)) {
        this.ZIP_CODE = data().deepCopy(fields()[13].schema(), other.ZIP_CODE);
        fieldSetFlags()[13] = true;
      }
    }
    
    /** Creates a Builder by copying an existing KsqlDataSourceSchema_CONTACT_INFORMATIONS instance */
    private Builder(io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS other) {
            super(io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.SCHEMA$);
      if (isValidValue(fields()[0], other.CITY)) {
        this.CITY = data().deepCopy(fields()[0].schema(), other.CITY);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.CIVILITY)) {
        this.CIVILITY = data().deepCopy(fields()[1].schema(), other.CIVILITY);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.COUNTRY)) {
        this.COUNTRY = data().deepCopy(fields()[2].schema(), other.COUNTRY);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.EMAIL)) {
        this.EMAIL = data().deepCopy(fields()[3].schema(), other.EMAIL);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.FAX)) {
        this.FAX = data().deepCopy(fields()[4].schema(), other.FAX);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.FIRSTNAME)) {
        this.FIRSTNAME = data().deepCopy(fields()[5].schema(), other.FIRSTNAME);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.LASTNAME)) {
        this.LASTNAME = data().deepCopy(fields()[6].schema(), other.LASTNAME);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.PHONE)) {
        this.PHONE = data().deepCopy(fields()[7].schema(), other.PHONE);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.PHONE_SECONDARY)) {
        this.PHONE_SECONDARY = data().deepCopy(fields()[8].schema(), other.PHONE_SECONDARY);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.STATE)) {
        this.STATE = data().deepCopy(fields()[9].schema(), other.STATE);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.STREET1)) {
        this.STREET1 = data().deepCopy(fields()[10].schema(), other.STREET1);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.STREET2)) {
        this.STREET2 = data().deepCopy(fields()[11].schema(), other.STREET2);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.WEB_SITE)) {
        this.WEB_SITE = data().deepCopy(fields()[12].schema(), other.WEB_SITE);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.ZIP_CODE)) {
        this.ZIP_CODE = data().deepCopy(fields()[13].schema(), other.ZIP_CODE);
        fieldSetFlags()[13] = true;
      }
    }

    /** Gets the value of the 'CITY' field */
    public java.lang.CharSequence getCITY() {
      return CITY;
    }
    
    /** Sets the value of the 'CITY' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder setCITY(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.CITY = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'CITY' field has been set */
    public boolean hasCITY() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'CITY' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder clearCITY() {
      CITY = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'CIVILITY' field */
    public java.lang.CharSequence getCIVILITY() {
      return CIVILITY;
    }
    
    /** Sets the value of the 'CIVILITY' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder setCIVILITY(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.CIVILITY = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'CIVILITY' field has been set */
    public boolean hasCIVILITY() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'CIVILITY' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder clearCIVILITY() {
      CIVILITY = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'COUNTRY' field */
    public java.lang.CharSequence getCOUNTRY() {
      return COUNTRY;
    }
    
    /** Sets the value of the 'COUNTRY' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder setCOUNTRY(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.COUNTRY = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'COUNTRY' field has been set */
    public boolean hasCOUNTRY() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'COUNTRY' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder clearCOUNTRY() {
      COUNTRY = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'EMAIL' field */
    public java.lang.CharSequence getEMAIL() {
      return EMAIL;
    }
    
    /** Sets the value of the 'EMAIL' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder setEMAIL(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.EMAIL = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'EMAIL' field has been set */
    public boolean hasEMAIL() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'EMAIL' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder clearEMAIL() {
      EMAIL = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'FAX' field */
    public java.lang.CharSequence getFAX() {
      return FAX;
    }
    
    /** Sets the value of the 'FAX' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder setFAX(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.FAX = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'FAX' field has been set */
    public boolean hasFAX() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'FAX' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder clearFAX() {
      FAX = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'FIRSTNAME' field */
    public java.lang.CharSequence getFIRSTNAME() {
      return FIRSTNAME;
    }
    
    /** Sets the value of the 'FIRSTNAME' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder setFIRSTNAME(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.FIRSTNAME = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'FIRSTNAME' field has been set */
    public boolean hasFIRSTNAME() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'FIRSTNAME' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder clearFIRSTNAME() {
      FIRSTNAME = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'LASTNAME' field */
    public java.lang.CharSequence getLASTNAME() {
      return LASTNAME;
    }
    
    /** Sets the value of the 'LASTNAME' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder setLASTNAME(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.LASTNAME = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'LASTNAME' field has been set */
    public boolean hasLASTNAME() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'LASTNAME' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder clearLASTNAME() {
      LASTNAME = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'PHONE' field */
    public java.lang.CharSequence getPHONE() {
      return PHONE;
    }
    
    /** Sets the value of the 'PHONE' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder setPHONE(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.PHONE = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'PHONE' field has been set */
    public boolean hasPHONE() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'PHONE' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder clearPHONE() {
      PHONE = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'PHONE_SECONDARY' field */
    public java.lang.CharSequence getPHONESECONDARY() {
      return PHONE_SECONDARY;
    }
    
    /** Sets the value of the 'PHONE_SECONDARY' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder setPHONESECONDARY(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.PHONE_SECONDARY = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'PHONE_SECONDARY' field has been set */
    public boolean hasPHONESECONDARY() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'PHONE_SECONDARY' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder clearPHONESECONDARY() {
      PHONE_SECONDARY = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'STATE' field */
    public java.lang.CharSequence getSTATE() {
      return STATE;
    }
    
    /** Sets the value of the 'STATE' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder setSTATE(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.STATE = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'STATE' field has been set */
    public boolean hasSTATE() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'STATE' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder clearSTATE() {
      STATE = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'STREET1' field */
    public java.lang.CharSequence getSTREET1() {
      return STREET1;
    }
    
    /** Sets the value of the 'STREET1' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder setSTREET1(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.STREET1 = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'STREET1' field has been set */
    public boolean hasSTREET1() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'STREET1' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder clearSTREET1() {
      STREET1 = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'STREET2' field */
    public java.lang.CharSequence getSTREET2() {
      return STREET2;
    }
    
    /** Sets the value of the 'STREET2' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder setSTREET2(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.STREET2 = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'STREET2' field has been set */
    public boolean hasSTREET2() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'STREET2' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder clearSTREET2() {
      STREET2 = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'WEB_SITE' field */
    public java.lang.CharSequence getWEBSITE() {
      return WEB_SITE;
    }
    
    /** Sets the value of the 'WEB_SITE' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder setWEBSITE(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.WEB_SITE = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'WEB_SITE' field has been set */
    public boolean hasWEBSITE() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'WEB_SITE' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder clearWEBSITE() {
      WEB_SITE = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'ZIP_CODE' field */
    public java.lang.CharSequence getZIPCODE() {
      return ZIP_CODE;
    }
    
    /** Sets the value of the 'ZIP_CODE' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder setZIPCODE(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.ZIP_CODE = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'ZIP_CODE' field has been set */
    public boolean hasZIPCODE() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'ZIP_CODE' field */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema_CONTACT_INFORMATIONS.Builder clearZIPCODE() {
      ZIP_CODE = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    @Override
    public KsqlDataSourceSchema_CONTACT_INFORMATIONS build() {
      try {
        KsqlDataSourceSchema_CONTACT_INFORMATIONS record = new KsqlDataSourceSchema_CONTACT_INFORMATIONS();
        record.CITY = fieldSetFlags()[0] ? this.CITY : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.CIVILITY = fieldSetFlags()[1] ? this.CIVILITY : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.COUNTRY = fieldSetFlags()[2] ? this.COUNTRY : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.EMAIL = fieldSetFlags()[3] ? this.EMAIL : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.FAX = fieldSetFlags()[4] ? this.FAX : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.FIRSTNAME = fieldSetFlags()[5] ? this.FIRSTNAME : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.LASTNAME = fieldSetFlags()[6] ? this.LASTNAME : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.PHONE = fieldSetFlags()[7] ? this.PHONE : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.PHONE_SECONDARY = fieldSetFlags()[8] ? this.PHONE_SECONDARY : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.STATE = fieldSetFlags()[9] ? this.STATE : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.STREET1 = fieldSetFlags()[10] ? this.STREET1 : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.STREET2 = fieldSetFlags()[11] ? this.STREET2 : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.WEB_SITE = fieldSetFlags()[12] ? this.WEB_SITE : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.ZIP_CODE = fieldSetFlags()[13] ? this.ZIP_CODE : (java.lang.CharSequence) defaultValue(fields()[13]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
